name: pytest

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker container
        run: docker build -t docker-lineage-cicd-temp .

      - name: Run tests
        run: docker run --entrypoint pytest-3 docker-lineage-cicd-temp /root
